manager_hostname: api
compute1_hostname: compute1
stack_pass: password
stack_sshkey: >-
  AAAAB3NzaC1yc2EAAAABIwAAAQEArseBVfx9DLhFu1kjw0Pe2UCpo1PGfod8wyC9SHyozwD1Bj88jizxREdEfVQ+Eg4C6PHhZ0aHocvXRv5sB6FZCcohY2fyN4P0cwXIC+Dm2ZDgN6pAcjLvzvtV7ZVSk7yV/B4/dzwStR2SnBvRDUmiVpBk1uxVy9y4a1sl+CX831JefO62ZupQjCaTxd9vSAIeP84IsZsQ50xbikm8HxInolLVxLBQWEaYUi5n6UoGLBCVG55ek2ay7vPVPP3M0IurtIGEV0vJK/WS1aWHO1eqqNVTz5Qt1o1m9pbMmWGSQaMh3Rv+iwGF7tLrMq5d9f7Quhzta5A4ntBCRuoDK924ZQ==
# Define the setup mode to install the environment
# valid values: grenade/devstack default is devstack
setup_mode: devstack
# what interface on the host should be used for a bridge
# will often be eth0, but vagrant needs to know for sure
# This needs to be the full string descriptor of the interface.
# On some systems this can be something annoying like
# 'en1: Wi-Fi (Airport)'. Vagrant will not use this setting
# unless you get it exactly right.
#config.yaml.samplebridge_int: eth1
# A non upstream for the base box, used to speed things up.
# Choose one of box_name (for a locally added box) or box_url
# for the url of a nearby box.
box_name: "hashicorp/precise64"
#box_url: http://gallifrey/vagrant/devstack-2014-02-19.box

# Local devstack options
# a non upstream git url to fetch devstack from instead
#devstack_git: /home/vagrant/openstack/devstack
# if you have code on a different branch than master, you can set it here
#devstack_branch: compute_err_exit

# You can specify stable mac addresses to keep this from resetting
# on every create
# manager_mac: 0800274a508c
# compute1_mac: 0800274a508d
